# Generated by Django 3.0.7 on 2020-06-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='done',
        ),
        migrations.RemoveField(
            model_name='todo_list',
            name='made',
        ),
        migrations.RemoveField(
            model_name='todo_list',
            name='status',
        ),
        migrations.RemoveField(
            model_name='todo_list',
            name='warning',
        ),
    ]
